      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/tzm99/pyws:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=HTTP Server
            org.opencontainers.image.licenses=GPL
          cache-from: type=gha
          cache-to: type=gha,mode=max
